import Image from "next/image";

type Size = "sm" | "md" | "lg" | "xl";

const sizeMap: Record<Size, number> = { sm: 32, md: 44, lg: 72, xl: 128 };

/**
 * BrandMark — vectorized "at" mark (Inter Black glyph paths, font-independent).
 * Generated by scripts/generate-at-mark.py from Inter weight 900.
 * `glow` picks the variant with dark rounded-square background tile.
 */
export function BrandMark({
  size = "sm",
  glow = false,
}: {
  size?: Size;
  color?: string;
  glow?: boolean;
}) {
  const s = sizeMap[size];
  const src = glow ? "/brand/at-mark-tile.svg" : "/brand/at-mark.svg";
  return (
    <Image
      src={src}
      width={s}
      height={s}
      alt="atnetto.tech"
      priority
      style={{ width: s, height: s }}
      unoptimized
    />
  );
}

/**
 * BrandWordmark — official "@" + "atnetto.tech" text + tagline (optional).
 */
export function BrandWordmark({
  size = "md",
  withTagline = false,
}: {
  size?: "sm" | "md" | "lg";
  withTagline?: boolean;
}) {
  const fontSize = size === "sm" ? 16 : size === "md" ? 22 : 32;
  const markSize: Size = size === "lg" ? "md" : "sm";
  return (
    <span className="inline-flex items-center gap-2.5">
      <BrandMark size={markSize} />
      <span className="inline-flex flex-col leading-none">
        <span
          className="font-extrabold tracking-tight"
          style={{
            fontFamily: "var(--font-inter), Inter, sans-serif",
            color: "#F5F5F5",
            fontSize,
            letterSpacing: "-0.03em",
          }}
        >
          atnetto<span style={{ color: "#FF9A00" }}>.tech</span>
        </span>
        {withTagline && (
          <span
            className="mt-1.5"
            style={{
              fontSize: fontSize * 0.32,
              letterSpacing: "0.18em",
              color: "#767676",
              fontFamily: "var(--font-inter), Inter, sans-serif",
            }}
          >
            TECNOLOGIA · AUTOMAÇÃO · SUPORTE
          </span>
        )}
      </span>
    </span>
  );
}

/**
 * CornerBrackets — decorative motif (kept for sparing use).
 */
export function CornerBrackets({
  color = "rgba(255,154,0,0.35)",
  size = 28,
  thickness = 2,
  inset = 0,
}: {
  color?: string;
  size?: number;
  thickness?: number;
  inset?: number;
}) {
  const common: React.CSSProperties = {
    position: "absolute",
    width: size,
    height: size,
    pointerEvents: "none",
  };
  return (
    <>
      <span style={{ ...common, top: inset, left: inset, borderTop: `${thickness}px solid ${color}`, borderLeft: `${thickness}px solid ${color}` }} />
      <span style={{ ...common, top: inset, right: inset, borderTop: `${thickness}px solid ${color}`, borderRight: `${thickness}px solid ${color}` }} />
      <span style={{ ...common, bottom: inset, left: inset, borderBottom: `${thickness}px solid ${color}`, borderLeft: `${thickness}px solid ${color}` }} />
      <span style={{ ...common, bottom: inset, right: inset, borderBottom: `${thickness}px solid ${color}`, borderRight: `${thickness}px solid ${color}` }} />
    </>
  );
}
